<?php

namespace AllForKids\MainBundle\Repository;

/**
 * LigneCommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCommandesRepository extends \Doctrine\ORM\EntityRepository
{

}
