<?php
namespace AllForKids\MainBundle\Repository;
/**
 * Created by PhpStorm.
 * User: Narjes
 * Date: 2/13/2018
 * Time: 9:35 PM
 */
/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')->where('u.id IN (:array)')
            ->setParameter('array',$array);
        return $qb->getQuery()->getResult();
    }

    public function DQL($categories){
        $query=$this->getEntityManager()
            ->createQuery("
            select p from AllForKidsMainBundle:Produits p
            where p.categorie=:P 
            ")->setParameter('P',$categories);
        return $query->getResult();

    }

}